### ISSUE TITLE
Add support for REST

### ISSUE THREAD

**Issue by troglobit** [troglobit/uftpd#13]
When transferring a large file the transfer can be interrupted by network problems or the client pausing the transfer.  To restart a RETR, or STOR, we need to support REST.

This issue is instrumental to getting the VLC Android app. mentioned in issue #9 to work.

**Comment by oz123** [comment]
@troglobit I looked at the [source code for pyftpdlib for REST](https://github.com/giampaolo/pyftpdlib/blob/master/pyftpdlib/handlers.py#L2421). Seems easy enough to implement.
My real life work in C is very limited, but this would be a perfect learning ground (large enough code base, but not to large), to implement a real code. Would you accept a my PR for this?

**Comment by troglobit** [comment]
Yup, that's it. A restart marker/offset and then use it for the next STOR or RETR command, but then you also need to support ABOR to reset the operation ... that's how it started for me; "just a small little function, how hard could it be?!"

To answer your question: No. But only because I have a whole week of unpushed patches lined up in my own queue, one of them being REST. I've planned to finalize and push them this weekend.

**Comment by oz123** [comment]
Oh, well! Thanks for the honest answer. I will use your patched to learn by reading.

**Comment by troglobit** [comment]
Complete support added in refactor af54295.
