### ISSUE TITLE
-u to able login regested users + -ur to use users-root as ftp-root

### ISSUE THREAD

**Issue by blackcrack** [troglobit/uftpd#20]
Hi,
-u to able login regested users on standart root
-ur to use /home/%user%-root as ftp-root per user-account

to have a easy possible for make able the users to connect her/his home-dir per ftp/tftp
where can later start as -d as deamon to have a easy possible for setting up a easy user releated ftp..

( that should have happened years ago! and have started with mdk/~2000 )

thank you vers much for this nice and helpful proggy !

best regards
Blacky

**Comment by troglobit** [comment]
Hi,

I'm sorry but I really don't understand what you mean. Could you explain a bit more?  I can start by explaining how uftpd works today.

Two modes exist:
1. as a standard UNIX daemon, listening to port 21, it looks in /etc/passwd for the `ftp` user and will serve files from that user's `$HOME`, as found in /etc/passwd
2. as a user daemon, started e.g. on login from ~/.bash_profile or similar, the FTP root can be given as argument on the command line

uftpd is very simple, it does not support FTP login, only anonymous is supported.  Maybe this is what you were after?  I have currently no plans to add this myself, mostly because I don't need it, but also because I want to keep uftpd small and simple.  There are other (better) FTP daemons out there that do advanced features better, e.g. vsftpd.

**Comment by blackcrack** [comment]
1. oh, so it is not a Linux systemd/initd deamon ? 
 So LinusB.T. Kernel and a fs with tools as Linux-Distribution ?
 Only for Unix ? The Unix from IBM and Oracle **\*grin***
( a bit joke :stuck_out_tongue_winking_eye: )

forget not, you should make able to users, and not all who be in the passwd,
so must you give spezial users, where be in the "ftp-group" and must work with /etc/group also

to have a ftp-group where be allow to have a log in and be in the ftp-group
i have not seen to be group specific, this could be a security leak, if you all enable per default
what it is in the /etc/users a login, so be it not only Real users where can login, it be also the others who be in the /etc/passwd's so it's my suggestion, work with /etc/group and /etc/passwd

for make it possible for a group to have a login, as example "tftpgroup"
and all users where be in the group of the tftpgroup, is in possible to have a login-possible
and can login.

-pgl=tftpgroup

if ($USER:passwd search in group == $pgl (tftpgroup) ) able the login =give login=> login
else
printf " you're not allowed to login / you're have not a group
"
something in this direction

1a.
with a "-u" with combination -o /headroot/ the Computer-users want have all the same root
without any options could be default /srv/uftpd-common/$USER  (or $USERNAME)

**--o**ption writeable is only on the common ftp-root what it is now, if will share the user or the admin
a folder for "public" access for common access ? ( for example, to swap drivers or open source code )

-pgl=tftpgroup  (PublicGroupLogin (for make it more secure and determine a login-group ))
-p=Public folder  ( -p=/srv/uftpd-common/uftpd-public (or /mnt/sda1 as a hd) )
-uw (user write spezific, it meant's the user can access all folders, read all, but delete only the own files and folders (uid))
-fow=750  (folder create and set up the chmod to 750)
-fiw=644  (files create and set up to chmod 644)
-udr=1:2 (up down razio, upload one file, download 2 files)

over system "/etc/group" so GID could also create groups in the system where can give also access on different folders
as example
-pg=ftpgroup1/folderyx1    ( so group of the system can see and access "uftpd-common/uftpd-public/folderyx1")

in -p=/srv/uftpd-common/uftpd-public/
so in /srv/uftpd-common/uftpd-public/~ &public group folders

-pg=ftpgroup1:folderyx1; ftpgroup2:folderyx1/forgroup2; ftpgroup2:folderyxa/forgroup2too;

(PublicGroups)

therewith it is give to have special guest/ftpgroup where be in the ftpgroup1 see and access the folderx1.. and the ftpgroup2, see and access to the folders for group 2 and can see and access also group1 and the folder folderyxa/forgroup2too
so 
/srv/uftpd-common/uftpd-public/folderyx1/forgroup2
/srv/uftpd-common/uftpd-public/folderyxa/forgroup2too

is this to heavy, delete it.. or close it.. If that's out of the question.. it's be only suggestions/ideas

best regards
Blacky

**Comment by troglobit** [comment]
I don't understand the joke. Linux is a UNIX system and uftpd runs fine under systemd, SysV init, Finit, or any other PID 1 process starter/supervisor that matter. I recommend, however, running `in.ftpd` and `in.tftpd` (symlinks to uftpd) from inetd instead.

Like I said in my first reply; "I want to keep uftpd small and simple. There are other (better) FTP daemons out there that do advanced features better, e.g. vsftpd.".  So I'll be closing this issue.

**Comment by blackcrack** [comment]
@troglobit 
unix like system.. and not a Unixsystem, otherwish would it be licensed under a copyright, but Linux is licenced under a copy left and is put together from diffirent parts.. 
sorry for the disturb ..

also Unix ähnlich.. aber nicht Unix
gute nacht..
