### ISSUE TITLE
No such file or directory (what?)

### ISSUE THREAD

**Issue by takusuman** [troglobit/uftpd#35]
I've just set it up here in my home server, i've also set the ftp directory and then ran it as root.
When i've tried to access it via tnftp and run `ls`, it returned "No such file or directory.".

What is happening here? Could someone tell me if it's just my fault and how could i fix it?

My server log:
![image](https://user-images.githubusercontent.com/47103338/118378680-d1461c00-b5ab-11eb-8bb7-9ff1e5353880.png)

My client: 
![image](https://user-images.githubusercontent.com/47103338/118378673-ba9fc500-b5ab-11eb-82d5-e2c2c7cb60a7.png)

Sorry for any bad english.

**Comment by troglobit** [comment]
How did you start it, as an inetd service, or stand-alone daemon, what arguments to uftpd did you use?

**Comment by takusuman** [comment]
> How did you start it, as an inetd service, or stand-alone daemon, what arguments to uftpd did you use?

I've started it as a stand-alone daemon, and used these args:
`uftpd -n -l debug`

**Comment by troglobit** [comment]
Then tries to run from the ftp user's $HOME directory. I'm guessing you don't have an ftp user in your system?

**Comment by takusuman** [comment]
> 
> 
> Then tries to run from the ftp user's $HOME directory. I'm guessing you don't have an ftp user in your system?

Yes, i have.
![image](https://user-images.githubusercontent.com/47103338/118402146-0bacc900-b63f-11eb-962b-038683a90a65.png)

**Comment by takusuman** [comment]
It also says that it's serving files from my FTP directory, so i don't think that's this is the problem.
![image](https://user-images.githubusercontent.com/47103338/118402280-9a214a80-b63f-11eb-8b76-c89df0ca4a93.png)

**Comment by troglobit** [comment]
Weird, works for me over here.  Same setup, but a system user at lower UID and /srv/ftp as home directory.  I'm using ncftp to test...

Edit: just tested with tnftp, and it works as well.  Sorry, don't know what could be the problem here.

**Comment by takusuman** [comment]
> 
> 
> Weird, works for me over here. Same setup, but a system user at lower UID and /srv/ftp as home directory. I'm using ncftp to test...
> 
> Edit: just tested with tnftp, and it works as well. Sorry, don't know what could be the problem here.

I will try to recompile it.

Edit: Yeah, still getting the same error.

**Comment by troglobit** [comment]
Really running out of ideas, have you checked that uftpd has read (and execute for dirs) permissions for the `/usr/str0/ftp` directory?

**Comment by takusuman** [comment]
I think yes, because it's running as root; so, in theory, it has to have them.

**Comment by troglobit** [comment]
Actually, when running as root and an ftp user exists, uftpd drops privilieges to that user.

**Comment by takusuman** [comment]
Oh...
O.k., i will test here.

Edit: Now it works.
Sorry for being an idiot, but at least may this thread solves another person's problem.

**Comment by troglobit** [comment]
No problem, it's not obvious how it works.  Great to hear you got it working at least, take care! :)
